//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_Book
    {
        public string id { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public string status { get; set; }
    
        public virtual account account { get; set; }
    }
}
