//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_ROLE
    {
        public APP_ROLE()
        {
            this.USER_ROLE = new HashSet<USER_ROLE>();
            this.USER_ROLE1 = new HashSet<USER_ROLE>();
        }
    
        public long ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
    
        public virtual ICollection<USER_ROLE> USER_ROLE { get; set; }
        public virtual ICollection<USER_ROLE> USER_ROLE1 { get; set; }
    }
}
