//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string id { get; set; }
        public string username { get; set; }
        public string idproduct { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public double totalcost { get; set; }
    }
}
