//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectWebBanGiayEntities : DbContext
    {
        public ProjectWebBanGiayEntities()
            : base("name=ProjectWebBanGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_TransactionIndex_237b54d1_d71b_4693_9336_2c1897920f9b> C_TransactionIndex_237b54d1_d71b_4693_9336_2c1897920f9b { get; set; }
        public DbSet<account> accounts { get; set; }
        public DbSet<address_Book> address_Book { get; set; }
        public DbSet<APP_ROLE> APP_ROLE { get; set; }
        public DbSet<APP_USER> APP_USER { get; set; }
        public DbSet<bill> bills { get; set; }
        public DbSet<bill_Details> bill_Details { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<Persistent_Logins> Persistent_Logins { get; set; }
        public DbSet<replycomment> replycomments { get; set; }
        public DbSet<review> reviews { get; set; }
        public DbSet<sho> shoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<USER_ROLE> USER_ROLE { get; set; }
        public DbSet<viewHistory> viewHistories { get; set; }
        public DbSet<findAssociation> findAssociations { get; set; }
        public DbSet<option> options { get; set; }
    }
}
