//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database_CDWEntities1 : DbContext
    {
        public database_CDWEntities1()
            : base("name=database_CDWEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<address_Book> address_Book { get; set; }
        public virtual DbSet<APP_ROLE> APP_ROLE { get; set; }
        public virtual DbSet<APP_USER> APP_USER { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bill_Details> bill_Details { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<Persistent_Logins> Persistent_Logins { get; set; }
        public virtual DbSet<replycomment> replycomments { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<sho> shoes { get; set; }
        public virtual DbSet<USER_ROLE> USER_ROLE { get; set; }
        public virtual DbSet<viewHistory> viewHistories { get; set; }
        public virtual DbSet<findAssociation> findAssociations { get; set; }
        public virtual DbSet<option> options { get; set; }
    }
}
