//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class replycomment
    {
        public string id { get; set; }
        public string idcomment { get; set; }
        public string username { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
    }
}
