//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sho
    {
        public string id { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string material { get; set; }
        public string color { get; set; }
        public string brand { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string manufactory { get; set; }
        public string imageslink { get; set; }
        public Nullable<double> pricebefore { get; set; }
        public string category { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string depth { get; set; }
        public string checkquality { get; set; }
        public string description { get; set; }
        public Nullable<int> rate { get; set; }
        public string status { get; set; }
    }
}
